url: http://albertogrespan.com
email: alberto@albertogrespan.com

connect:
  twitter: https://twitter.com/albertogg
  github: https://github.com/albertogg
  feed: http://albertogrespan.com/feed.atom
  disqus: albertogrespan

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - CC-LICENSE
  - MIT-LICENSE
  - Procfile
  - Rakefile
  - CNAME

permalink: /:categories/:title
excerpt_separator: ""
pygments: true
markdown: redcarpet
safe: true
lsi: false
