email: alberto@albertogrespan.com
title: alberto grespan dot com
name: Alberto Grespan
gravatar:
  title: albertogg
  url: http://www.gravatar.com/avatar/006ef14fba8fadd40053ecda5039deb2.png

connect:
  twitter: https://twitter.com/albertogg
  github: https://github.com/albertogg
  feed: http://albertogrespan.com/feed.atom
  disqus: albertogrespan

analytics:
  google:
    id: UA-29129831-1
    domain: albertogrespan.com

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - CC-LICENSE
  - MIT-LICENSE
  - Procfile
  - Rakefile
  - CNAME

permalink: /:categories/:title

highlighter: rouge
markdown: redcarpet

excerpt_separator: ""

host: 0.0.0.0
port: 3000
baseurl: /
url: http://albertogrespan.com
lsi: false

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
