url: http://albertogrespan.com

networks:
  twitter: albertogg
  github: albertogg
  feed: feed.atom

permalink: /:categories/:title
excerpt_separator: ""
pygments: true
markdown: redcarpet
safe: true
lsi: false
