# site config variables everything here is reachable using site.variable-name
name: Alberto Grespan # this variable is used by the jekyll feed

author:
  name: Alberto Grespan
  handle: albertogg
  email: alberto@albertogrespan.com
  uri: https://twitter.com/albertogg

gravatar:
  title: albertogg
  url: http://www.gravatar.com/avatar/006ef14fba8fadd40053ecda5039deb2.png

connect:
  twitter: https://twitter.com/albertogg
  github: https://github.com/albertogg
  feed: http://albertogrespan.com/feed.atom
  disqus: albertogrespan

analytics:
  google:
    id: UA-29129831-1
    domain: albertogrespan.com

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - CC-LICENSE
  - MIT-LICENSE
  - Procfile
  - Rakefile
  - CNAME

sass:
  sass_dir: css/scss
  style: compressed

feed:
  path: feed.atom

permalink: /:categories/:title/

# Markdown Processors
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false

excerpt_separator: ""

host: 0.0.0.0
port: 3000
baseurl: ""
url: http://albertogrespan.com
lsi: false
incremental: true

gems:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
