baseURL: http://albertogrespan.com
disablePathToLower: true
languageCode: en-us
title: Blog

params:
  author: Alberto Grespan
  googleAnalytics: UA-29129831-1
  gravatar:
    url: http://www.gravatar.com/avatar/006ef14fba8fadd40053ecda5039deb2.png
    title: albertogg
  connect:
    email: alberto@albertogrespan.com
    feed: http://albertogrespan.com/feed.atom
    twitter:
      url: https://twitter.com/albertogg
      handle: albertogg
    github:
      url: https://github.com/albertogg
      handle: albertogg
