baseURL: http://albertogrespan.com
disablePathToLower: true
languageCode: en-us
title: Blog

author:
  name: Alberto Grespan
  email: alberto@albertogrespan.com

params:
  author: Alberto Grespan
  analytics:
    google:
      id: UA-29129831-1
      domain: albertogrespan.com
  gravatar:
    url: http://www.gravatar.com/avatar/006ef14fba8fadd40053ecda5039deb2.png
    title: albertogg
  connect:
    email: alberto@albertogrespan.com
    feed: http://albertogrespan.com/feed.atom
    twitter:
      url: https://twitter.com/albertogg
      handle: albertogg
    github:
      url: https://github.com/albertogg
      handle: albertogg

# Taxonomies activation
taxonomies:
  tag: "tags"
  category: "categories"
  series: "series"
